name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/create-gh-release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    strategy:
      matrix:
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> fd0b0f7... Update release_on_tag.yml
=======
>>>>>>> 5edf403... Create release_on_tag.yml
=======
=======
>>>>>>> fd0b0f7... Update release_on_tag.yml
>>>>>>> f83155c... Create release_on_tag.yml
=======
>>>>>>> 11bcc69... Squashed commit of the following:
=======
>>>>>>> fd0b0f7... Update release_on_tag.yml
=======
>>>>>>> 5edf403... Create release_on_tag.yml
=======
=======
>>>>>>> fd0b0f7... Update release_on_tag.yml
>>>>>>> f83155c... Create release_on_tag.yml
=======
>>>>>>> fd0b0f7... Update release_on_tag.yml
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-20.04
            build_tool: cross
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 5dd386d... Update release_on_tag.yml
=======
>>>>>>> 5edf403... Create release_on_tag.yml
=======
=======
>>>>>>> 5dd386d... Update release_on_tag.yml
>>>>>>> f83155c... Create release_on_tag.yml
=======
>>>>>>> 11bcc69... Squashed commit of the following:
=======
>>>>>>> 5dd386d... Update release_on_tag.yml
=======
>>>>>>> 5edf403... Create release_on_tag.yml
=======
=======
>>>>>>> 5dd386d... Update release_on_tag.yml
>>>>>>> f83155c... Create release_on_tag.yml
=======
>>>>>>> 5dd386d... Update release_on_tag.yml
            name: ubuntu-18.04+
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-22.04
            build_tool: cargo
            name: ubuntu-22.04+
          - target: x86_64-pc-windows-gnu
            os: windows-latest
            build_tool: cargo
            name: windows
          
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> f83155c... Create release_on_tag.yml
=======
>>>>>>> 11bcc69... Squashed commit of the following:
=======
>>>>>>> f83155c... Create release_on_tag.yml
=======
        os:
          - ubuntu-22.04
          - ubuntu-20.04
          - windows-latest
>>>>>>> 45113aa... Create release_on_tag.yml
=======
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-22.04
            build_tool: cargo
          - target: x86_64-pc-windows-gnu
            os: windows-latest
            build_tool: cargo
          
>>>>>>> fd0b0f7... Update release_on_tag.yml
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 5edf403... Create release_on_tag.yml
=======
>>>>>>> f83155c... Create release_on_tag.yml
=======
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-22.04
            build_tool: cargo
          - target: x86_64-pc-windows-gnu
            os: windows-latest
            build_tool: cargo
          
>>>>>>> fd0b0f7... Update release_on_tag.yml
=======
>>>>>>> 11bcc69... Squashed commit of the following:
=======
>>>>>>> 5edf403... Create release_on_tag.yml
=======
>>>>>>> f83155c... Create release_on_tag.yml
=======
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-22.04
            build_tool: cargo
          - target: x86_64-pc-windows-gnu
            os: windows-latest
            build_tool: cargo
          
>>>>>>> fd0b0f7... Update release_on_tag.yml
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> f83155c... Create release_on_tag.yml
          #bin: system_monitor_${{  github.ref_name }}
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
          #bin: system_monitor_${{  github.ref_name }}
<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> 11bcc69... Squashed commit of the following:
=======
          #bin: system_monitor_${{  github.ref_name }}
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> f83155c... Create release_on_tag.yml
          archive: $bin-$tag-${{ matrix.name }}
=======
          archive: $bin-$tag-${{ matrix.os }}
>>>>>>> 6ddb521... Update release_on_tag.yml
          bin: system_monitor
=======
          bin: system_monitor_unix, system_monitor_windows
>>>>>>> 45113aa... Create release_on_tag.yml
=======
          bin: system_monitor
>>>>>>> 962f5da... Update release_on_tag.yml
=======
          bin: system_monitor_${{  github.ref_name }}
>>>>>>> 25a8693... Update release_on_tag.yml
=======
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 11bcc69... Squashed commit of the following:
          #bin: system_monitor_${{  github.ref_name }}
=======
          archive: $bin-$tag-${{ matrix.name }}
>>>>>>> 5dd386d... Update release_on_tag.yml
          bin: system_monitor
>>>>>>> e74f9b2... Update release_on_tag.yml
<<<<<<< HEAD
=======
=======
>>>>>>> f83155c... Create release_on_tag.yml
          #bin: system_monitor_${{  github.ref_name }}
=======
          archive: $bin-$tag-${{ matrix.name }}
>>>>>>> 5dd386d... Update release_on_tag.yml
=======
          archive: $bin-$tag-${{ matrix.name }}
>>>>>>> 5dd386d... Update release_on_tag.yml
          bin: system_monitor
<<<<<<< HEAD
>>>>>>> 5edf403... Create release_on_tag.yml
=======
>>>>>>> e74f9b2... Update release_on_tag.yml
>>>>>>> f83155c... Create release_on_tag.yml
=======
>>>>>>> 11bcc69... Squashed commit of the following:
=======
=======
>>>>>>> f83155c... Create release_on_tag.yml
          #bin: system_monitor_${{  github.ref_name }}
=======
          archive: $bin-$tag-${{ matrix.name }}
>>>>>>> 5dd386d... Update release_on_tag.yml
=======
          archive: $bin-$tag-${{ matrix.name }}
>>>>>>> 5dd386d... Update release_on_tag.yml
          bin: system_monitor
<<<<<<< HEAD
>>>>>>> 5edf403... Create release_on_tag.yml
=======
>>>>>>> e74f9b2... Update release_on_tag.yml
>>>>>>> f83155c... Create release_on_tag.yml
          tar: unix
          zip: windows
          token: ${{ secrets.GITHUB_TOKEN }}
